spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentcloud_customer?createDatabaseIfNotExist=true
    username: root
    password: 1qazxsw2#
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
   # properties:
   #  hibernate:
   #   dialect: org.hibernate.dialect.MySQL55Dialect
