server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/krish/spring-cloud-config-store
          search-paths:
           - '*service'
          #username: root
          #passphrase: 12345